### ISSUE TITLE
Breaking change with Lambda nodejs runtime

### ISSUE THREAD

**Issue by MovingToWeb** [aws-samples/example-step-functions-integration-api-gateway#6]
Hi team,
When I try the sample from AWS Console via the Step Functions UI, i get the following error:
`
Resource handler returned message: "The runtime parameter of nodejs10.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs14.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: 9e52a271-1e57-49ab-8ac2-d65bc5e0d7dd, Extended Request ID: null)" (RequestToken: ec51aae9-4ddd-3856-20a0-c4c20006111a, HandlerErrorCode: InvalidRequest)
`
Please update the nodejs runtime version to 14.x in the template.yaml file

**Comment by benjasl-stripe** [comment]
resolved.
